trigger:
- main

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest' 
    
steps :
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')
